"""
setup_builder.py
────────────────
Generates a PyInstaller .spec for your main app and a launcher.py
that caches the main app to the user's local temp folder before running.

Usage:
    python setup_builder.py path/to/main_app.py [--app-name MyApp] [--icon path/to/icon.ico]

What gets created next to this script:
    main_app.spec       ← build spec for your main application
    launcher.py         ← launcher source (cache + run)
    launcher.spec       ← build spec for the launcher

Expected final folder structure on the network share:
    \\\\shared\\drive\\app\\
        launcher.exe
        _internal\\          (launcher deps — small & quick)
        main_app\\
            main_app.exe
            _internal\\      (main app deps — cached to %TEMP% on first run)
"""

import argparse
import os
import sys
import textwrap


# ── helpers ───────────────────────────────────────────────────────────────────

def write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"  [created] {path}")


# ── generators ────────────────────────────────────────────────────────────────

def make_main_spec(app_name: str, main_app_abs: str, icon_arg: str) -> str:
    """Folder-mode spec for the main application."""
    icon_line = f"    icon={icon_arg!r}," if icon_arg else "    # icon='path/to/icon.ico',"
    return textwrap.dedent(f"""\
        # ── main_app.spec ────────────────────────────────────────────────────────────
        # Auto-generated by setup_builder.py
        # Build:  pyinstaller main_app.spec

        block_cipher = None

        a = Analysis(
            [{main_app_abs!r}],
            pathex=[],
            binaries=[],
            datas=[],
            hiddenimports=[],
            hookspath=[],
            hooksconfig={{}},
            runtime_hooks=[],
            excludes=[
                'tkinter', 'unittest', 'email', 'html', 'http',
                'urllib', 'xml', 'pydoc', 'doctest', 'difflib',
            ],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz,
            a.scripts,
            [],                  # empty → folder mode (no onefile)
            exclude_binaries=True,
            name={app_name!r},
        {icon_line}
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=False,           # UPX disabled
            console=True,        # set False for GUI apps
            disable_windowed_traceback=False,
            argv_emulation=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
        )

        coll = COLLECT(
            exe,
            a.binaries,
            a.zipfiles,
            a.datas,
            strip=False,
            upx=False,
            upx_exclude=[],
            name={app_name!r},   # output subfolder: dist/{app_name}/
        )
    """)


def make_launcher_py(app_name: str, icon_arg: str) -> str:
    """
    Launcher source — copies the main_app subfolder to %TEMP% on first run
    (or when the exe is newer), then executes from the local copy.
    """
    return textwrap.dedent(f"""\
        """
        + '"""' + f"""
        launcher.py  —  auto-generated by setup_builder.py

        Copies the '{app_name}' folder from the network share to the user's
        local temp directory, then runs the cached copy.  Re-syncs automatically
        whenever main_app.exe is newer than the cached copy.
        """
        + '"""' + """

        import os
        import sys
        import shutil
        import subprocess
        import tempfile

        APP_NAME   = """ + repr(app_name) + """
        EXE_NAME   = APP_NAME + ".exe"          # Windows; drop .exe on Linux/Mac
        CACHE_ROOT = os.path.join(tempfile.gettempdir(), "pyapp_cache")

        def main():
            # ── locate source (next to launcher.exe on the network share) ──────────
            base_dir  = os.path.dirname(os.path.abspath(sys.executable
                                        if getattr(sys, "frozen", False)
                                        else __file__))
            src_dir   = os.path.join(base_dir, APP_NAME)          # e.g. \\\\share\\app\\main_app
            src_exe   = os.path.join(src_dir, EXE_NAME)

            if not os.path.isdir(src_dir):
                sys.exit(f"[launcher] ERROR: cannot find app folder: {src_dir}")
            if not os.path.isfile(src_exe):
                sys.exit(f"[launcher] ERROR: cannot find exe: {src_exe}")

            # ── local cache path ──────────────────────────────────────────────────
            dst_dir   = os.path.join(CACHE_ROOT, APP_NAME)
            dst_exe   = os.path.join(dst_dir, EXE_NAME)

            # ── decide whether to (re)sync ────────────────────────────────────────
            needs_sync = (
                not os.path.isfile(dst_exe)
                or os.path.getmtime(src_exe) > os.path.getmtime(dst_exe)
            )

            if needs_sync:
                print(f"[launcher] Syncing {APP_NAME} to local cache …", flush=True)
                if os.path.exists(dst_dir):
                    shutil.rmtree(dst_dir)
                shutil.copytree(src_dir, dst_dir)
                print("[launcher] Sync complete.", flush=True)
            else:
                print("[launcher] Cache is up to date.", flush=True)

            # ── run from local cache ──────────────────────────────────────────────
            result = subprocess.run([dst_exe] + sys.argv[1:])
            sys.exit(result.returncode)


        if __name__ == "__main__":
            main()
    """)


def make_launcher_spec(launcher_py_abs: str, icon_arg: str) -> str:
    """Folder-mode spec for the launcher (intentionally lightweight)."""
    icon_line = f"    icon={icon_arg!r}," if icon_arg else "    # icon='path/to/icon.ico',"
    return textwrap.dedent(f"""\
        # ── launcher.spec ────────────────────────────────────────────────────────────
        # Auto-generated by setup_builder.py
        # Build:  pyinstaller launcher.spec

        block_cipher = None

        a = Analysis(
            [{launcher_py_abs!r}],
            pathex=[],
            binaries=[],
            datas=[],
            hiddenimports=[],
            hookspath=[],
            hooksconfig={{}},
            runtime_hooks=[],
            excludes=[
                'tkinter', 'unittest', 'email', 'html', 'http',
                'urllib', 'xml', 'pydoc', 'doctest', 'difflib',
            ],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz,
            a.scripts,
            [],                  # folder mode — keeps launcher deps in _internal
            exclude_binaries=True,
            name='launcher',
        {icon_line}
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=False,
            console=True,        # set False to hide the sync console window
            disable_windowed_traceback=False,
            argv_emulation=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
        )

        coll = COLLECT(
            exe,
            a.binaries,
            a.zipfiles,
            a.datas,
            strip=False,
            upx=False,
            upx_exclude=[],
            name='launcher',     # output subfolder: dist/launcher/
        )
    """)


def print_instructions(app_name: str, out_dir: str) -> None:
    sep = "─" * 60
    print(f"""
{sep}
  NEXT STEPS
{sep}

1) BUILD MAIN APP
   pyinstaller main_app.spec

   Output → dist/{app_name}/
             ├── {app_name}.exe
             └── _internal/

2) BUILD LAUNCHER
   pyinstaller launcher.spec

   Output → dist/launcher/
             ├── launcher.exe
             └── _internal/

3) DEPLOY TO NETWORK SHARE
   Copy the following layout to  \\\\shared\\drive\\app\\

       launcher.exe          ← from dist/launcher/launcher.exe
       _internal/            ← from dist/launcher/_internal/
       {app_name}/           ← entire dist/{app_name}/ folder
           {app_name}.exe
           _internal/

4) RUN
   Users double-click launcher.exe.
   On first run it copies '{app_name}/' to their %TEMP%\\pyapp_cache\\
   and launches from there.  Subsequent runs skip the copy if nothing changed.

{sep}
TIPS
  • Add --icon path/to/icon.ico to this script to embed icons in both exes.
  • Set  console=False  in both specs for pure GUI apps (hides the sync window).
  • The cache lives at: %TEMP%\\pyapp_cache\\{app_name}\\
  • To force a re-cache, users can delete that folder or you can bump
    the modified-time of {app_name}.exe (e.g. touch it after a deploy).
{sep}
""")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate PyInstaller spec + launcher for network-share deployment."
    )
    parser.add_argument("main_app", help="Path to your main_app.py")
    parser.add_argument("--app-name", default=None,
                        help="Override the exe name (default: stem of main_app.py)")
    parser.add_argument("--icon", default=None,
                        help="Path to .ico file (embedded in both exes)")
    args = parser.parse_args()

    # ── resolve paths ──────────────────────────────────────────────────────────
    main_app_abs = os.path.abspath(args.main_app)
    if not os.path.isfile(main_app_abs):
        sys.exit(f"ERROR: file not found: {main_app_abs}")

    app_name     = args.app_name or os.path.splitext(os.path.basename(main_app_abs))[0]
    icon_arg     = os.path.abspath(args.icon) if args.icon else None
    out_dir      = os.path.dirname(os.path.abspath(__file__))
    launcher_py  = os.path.join(out_dir, "launcher.py")

    print(f"\nsetup_builder  →  app: {app_name!r}")
    print(f"  main_app : {main_app_abs}")
    print(f"  icon     : {icon_arg or '(none)'}")
    print()

    # ── write files ───────────────────────────────────────────────────────────
    write(os.path.join(out_dir, "main_app.spec"),
          make_main_spec(app_name, main_app_abs, icon_arg))

    write(launcher_py,
          make_launcher_py(app_name, icon_arg))

    write(os.path.join(out_dir, "launcher.spec"),
          make_launcher_spec(launcher_py, icon_arg))

    print_instructions(app_name, out_dir)


if __name__ == "__main__":
    main()